//- フレームワーク
import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

//- コンポーネント
import HomeLayout from '../components/pages/Home/HomeLayout';

//- スタイル
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tripper</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
        <meta name='viewport' content='width=device-width,initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <main>
        <HomeLayout />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
